language: node_js
node_js:
  - "node"
cache: npm
script: npm run deploy
after_script: npm run alias
env:
  global:
    secure: AO/UFKi3RcQnb+9EXNLUnHnQf3GsROX0QTQ/HKEYbtPZ6wgt1EpGRQZaSjDM1dO1R3MQlpMSsw0cHME4hgiOQVqqHRCS6jmyNl7fgBDKlAp93uox6e829X8OsDF4O1dIOvkZon8oHAZSy/0Pr3mRwOULFMTCs2HLvfO2/0A0WWd5tRWbGZEdKDq3R+l12LFspGMjHxMWdcTF90ER9GMzPxiwZWgkrOGLPqw9s4C4n0fjpFVrrbwNvVYrWtZH9kiVgdxxM8r/0WaHj1EyY/mPPzqZUJUlz4xLcbPQmE72S2SsLPnLnkuxbleRjMxMtYKInrTq1rVQwyKqKjpwgfvklCgIeMgJqkDzJgaIij7MwFBwfYPE5D1SyjeDbDYO+zSMKqQAYrX6dKzNUTUMfiW6n5mtzUBwc2Xos/Lebykq2Uj1WG4+11MVmxy5OmWcNgZBw06QsT5tb5ohgTl7lfD2oACG6ph6Vr/Ymg/GXuna5OdUiy/1MamI6Bis5DXqB+iUeOucrdr+dmnnldsp3QIS/ZYuA46B1KRXib1cnViYEiEmw3mTgC2lg5gD2SuD0c7iYbcgFDir92rY2o3tzFeDCNO6+VYSK6WrVJfmrv5kU/WGm0nxEtoVTdPJHYp+HFSMbRY4/9N5F3ndId3Nrw45f7nIZpnAPg6HY8CpjIQ4fso=
