language: node_js
node_js:
- node
cache: npm
script: npm run deploy
after_script: npm run alias
env:
  global:
    - secure: 3/WFYpNNfOzVqSamVRUf0Y4GX7u68z+Ar2VDdKUxF3Pb9Q63XDNrE0RLrxgzH1w+NaqdM7kuMb+y2f3NHU414MHoGIG9PD9UHzVJY00Q5HqQs6hxQOWhUs7t03xHYur4V/20Fhr8Evc5DTZVsuLfikesRDfBN0Edf9tJh/rCN+PqwcWytPN6J0w0zzy/1C1mV/+QVV8MBNW4ScVqCaoqzu0M2yQb6PLvz6z9y2TWzP1fw7+VPF7v7qZBPeedKtuktaj53j7S6MMLkpKnb/NrN4NqzYayhzn8iUaOBeC5tIFPt2q7Vrf3efxqqeS3B3CU9xck1Ax0oE4izwaFUHb72X4DPq6vcr0TfQoOz+rbjana7uPYb+CdyXNLwTHf4g0SrEPHp3IZQl/1GyvWMZ4OE0tv4Ki3Dj/+g/mo4WKS19Q2vecqLU7/ej9P/sG7kyA+Vz+rglpc6Bk3wfyv6t/8UHdDqwvCjaji/6JoYArnqyrIZMRpkO18VaiAoHIs+I6vww5XcrLR/qWU5tuzY4VeJCdYVL+e7uE7oJ3EyMigQQV9FnT42jzcN3ypKgjIFLK74KTderSEADdZLgRD1iEPaWQaxp2CxepoWHl9KN29Vp+GF8fgzhCW0tzTpWsJYlLw7VAOSHCWCaFn/vCPsS+kHSjoDSdjaS4pjlbPKa6AA3w=
