language: node_js
node_js:
- node
cache: npm
script: npm run deploy
after_script: npm run alias
env:
  global:
    secure: PfgGgYDYuNWrsGVVu9ELqO8qWwiFhREPXw6j0rxsS0+fvK9UggD0x1hGeHVbnhIuuET0Qf8m7GO9wbS3LEyikS33eGI9KA1AqvZGzSOBCKeh4ulgBYWb7MMUYoPWYFAN5JWrYghO2N/d4Y1Tb+g24nHfvY9yqwjRgxRp3MDD0VRSwrguKCPNTLYES3GgTVzFJ8lZth2BgmBz0focqTtcJOnEx5JU25pkerOIPOJiJ4VD4Uw1/dIltnQ6Pz3T+3I2sXczMHnIxF5W0AsDyMrdiOzUf7bIUygQSEHS2FKMZioSSRK6DGTxxu4dcPVbXTMRe64OUvJNvaeQv5n71epcUernkhawRpNe06l+mU+e9tLb1H5dthQdzAbDq2OfOi6TjhkxabByf87FCpwHONagQtp9JMiR/gU/OoXgCUWFXQtTFNkLeii3HeFK8XonJVkXoCwh1Euv9d/3nL2UxHLsc9uxBPdKw3QSnBzBuZns8OU6WYGZL7sK0NEJXoofhRHI+HkP1NZcFTlvpe8wkjGmwiWnEJRbf0sxB9LIYlfhhmApwWgFxfXI/jOz6XMFPtuzZ1btjvmXpM9m1DwMZr4yOXRICISW8jF2sIAEgPMk00ua6weLCB1vubSxd2a0DWMrJqaFqHdyQ+PtDmh0Yr2iPm1ak4WSGv7iVVU6engL/c4=
