language: node_js
node_js:
- node
cache: npm
script: npm run deploy
after_script: npm run alias
env:
  global:
    secure: S6DwGr6a5+HTH/gXFrvkA3VrKkLK2QVAkKMfIAoN5I33oBGM5yzJEOjOwTq/+1nWOfbHIBocYhevszkSNSThDFoJosFr9bQ5FBXrgvWrNVnyLKPHgIbKdOSYQETiwAXvoAaGjCfXtXhgP8f+rrIoZ7tVyeK23AMZfM9vp05zGJOkBEiLI5O/WJtXP9yZgjvIpsXrt/Xr1R1a/kiB7Sj/PSC1+ZDycr4U8KUlod90OXlWeCXm5zn20pbLjSCJxKhYjwJAtDXoGl1gC4GFUhcKS1N3ayBi01APXY9ThDhW64TOzzLBFvopUEpv5JTqSeKYjz7AK+3UnUh7OM7lNoIIcX3I87vcz+iWfV94cMAzac9Lo/WIzR8l4y39TLKhN4Rzj8sB8Cm3fK2VW4v1+DVxMCkz+yhyB+Q2MG0X53C7cclJFUri4mP1gvyvOGIJu0wainxbry+HCLw0NHizVrquJfFSUeCotVSUPMSyIe/amu2LGGODxmfNJWT5bNSVDLLwCDRfHUYLSOPnoSZl7XZr8YR3OTv4POMXwOdXBRXUnzpcrNMWHX/Roj52+C4eUOCT3J8OtHD7Yr77C+JFKDIPR6iyvVMKxeULon1K3bX4lyHSY0PudeyCbyyHgEJRSZtpkVwsUN0IyirN9bT0QnPnFTNvlHAs/ljaSQSnOgq1wLY=
