language: node_js
node_js:
- node
cache: npm
script: npm run deploy
after_script: npm run alias
env:
  global:
    - secure: BrAyL+dB78eUJ85EGfbCADvMSLBMM3Qv8kirutyH1Ae8N7IP7W2hO8cq3qfaiRS2xaKz4JbeB5KmYYnwJpHV59zXlYgFRVOp4yDMqVShfCvRkzRDEDXRGM9qvCRjbt0adZE82FNV15cW8nufq7f2BEAjW3xVq2CshW6maKb1E2bRjxtsRRDcbe7p8gPhShEuPpLDq7r+6rWB2HcWeYxUvnErdRoegUVpjeoBF8Ek9Z+UBwSox/7Cu5yLS6a/Oe5ZWP92HA9+hhZ6lNjezsCupUtAt3Y2a4TaGODq3YsqUG9w2wYRuYxNmeGVNqWSjBdRqNiUr9J77HOXLnXoU8Xg/PTSrUcQryLNwAfoaJY0CQI4biejT99Osvsk1xNoCiiz7yTmDb9YuVMkbKNcE/wZYvIhms2Lxdg1029dWdpIHGNl/QlDlGhJLWpzrvZHgKTvkRWQY7P7aDU1inx3eDCbsD3qXi8OpNADtKr6LuyUrJ1tDdJI1dSlrCW225Qkhqla5/5FRGyxLBo0Con83ehzWdsfzr864Fu8N0xF5+sJGnZpKt54h9IkMXvKnGIJpIwYDxTdog6rNqGyBOD4kwvfxCbBCwx4Z/LIHdTFzzxLHUpFzGIAdTlK62IkTEvgbZt4cOY0eavQgovqtKQLpKA6qJnzY2CvouQpaRSDBXAensg=
